from __future__ import annotations
from unidecode import unidecode

FOLDER_RULES = {
    "Personal": [
        "INE",
        "Acta de nacimiento",
        "CURP",
        "Pasaporte mexicano",
        "Constancia de identidad",
        "Carta de no antecedentes penales",
        "Acta de matrimonio",
        "Acta de divorcio",
        "Acta de defunción de familiar",
        "Cartilla del Servicio Militar Nacional",
        "Comprobante de domicilio",
        "Testamento",
        "Poder notarial",
        "Carta de naturalización",
        "Visa vigente",
        "Aviso de cambio de domicilio ante el SAT",
        "Carta de autorización de uso de imagen",
        "Documento de adopción",
        "Comprobante de cambio de nombre",
        "Tarjeta INAPAM",
        "Credencial de discapacidad",
        "Registro de firma electrónica avanzada (e.firma)",
        "Declaratoria de concubinato",
        "Constancia de dependencia económica",
        "Carta de referencias personales",
        "Constancia de domicilio emitida por autoridad local",
        "Resolución de cambio de sexo genérico",
        "Oficio de reconocimiento de patria potestad",
        "Convenio de guarda y custodia",
        "Notificación oficial de adopción plena",
        "Acta de reconocimiento de hijo",
        "Declaratoria de ausencia por desaparición",
        "Documento de situación migratoria (NUT)",
        "Carta de identidad indígena (si aplica)",
    ],
    "Escolar": [
        "Constancia de estudios",
        "Certificado de primaria",
        "Certificado de secundaria",
        "Certificado de bachillerato",
        "Certificado de licenciatura",
        "Título profesional",
        "Carta de pasante",
        "Boletas de calificaciones",
        "Historial académico",
        "Kardex",
        "Constancia de servicio social",
        "Carta de liberación de servicio social",
        "Constancia de prácticas profesionales",
        "Carta de liberación de prácticas",
        "Acta de examen profesional",
        "Registro de titulación",
        "Constancia de seminario o taller",
        "Diploma de aprovechamiento",
        "Diploma de participación",
        "Diploma de asistencia",
        "Reconocimiento académico",
        "Comprobante de inscripción",
        "Ficha de reinscripción",
        "Recibo de colegiatura",
        "Recibo de inscripción",
        "Ficha de examen de admisión",
        "Carta de aceptación escolar",
        "Carta de baja temporal",
        "Carta de baja definitiva",
        "Carta de reingreso",
        "Constancia de beca",
        "Carta de postulación de beca",
        "Comprobante de beca",
        "Certificado de idioma",
        "Certificado de otros cursos extracurriculares",
        "Constancia de participación en olimpiadas del conocimiento",
        "Constancia de curso en línea",
        "Registro en plataforma educativa",
        "Reglamento escolar firmado",
        "Carta compromiso de padres",
        "Evaluación diagnóstica",
        "Informe de tutorías",
        "Ficha de evaluación final",
        "Constancia de fin de cursos",
        "Constancia de traslado escolar",
        "Certificado de preescolar",
        "Carta de buena conducta escolar",
        "Constancia de prácticas docentes",
        "Acta de comité escolar (participación)",
        "Formato de asignación de matrícula",
        "Credencial escolar",
        "Pase de acceso a biblioteca",
        "Constancia de movilidad académica",
        "Carta de aceptación a posgrado",
        "Comprobante de pago de trámite de titulación",
        "Protocolo de tesis registrado",
        "Carta de no adeudo de biblioteca",
        "Oficio de asignación de asesor de tesis",
    ],
    "Vivienda": [
        "Contrato de arrendamiento",
        "Contrato de compraventa de inmueble",
        "Escritura pública",
        "Certificado de libertad de gravamen",
        "Recibo de predial",
        "Recibo de agua",
        "Recibo de luz (CFE)",
        "Recibo de gas",
        "Recibo de teléfono fijo",
        "Carta de posesión",
        "Avalúo inmobiliario",
        "Póliza de seguro de vivienda",
        "Póliza jurídica de arrendamiento",
        "Recibo de mantenimiento de condominio",
        "Estado de cuenta INFONAVIT",
        "Estado de cuenta FOVISSSTE",
        "Aviso de retención INFONAVIT",
        "Aviso de suspensión INFONAVIT",
        "Contrato de crédito hipotecario",
        "Carta finiquito de crédito hipotecario",
        "Constancia de no adeudo de agua",
        "Constancia de no adeudo de predial",
        "Constancia de no adeudo de mantenimiento",
        "Recibo de cuota de condominio",
        "Reglamento de condominio",
        "Croquis del terreno",
        "Licencia de construcción",
        "Permiso de uso de suelo",
        "Avalúo catastral",
        "Comprobante de entrega de inmueble",
        "Contrato con inmobiliaria",
        "Contrato de preventa",
        "Carta de autorización de crédito hipotecario",
        "Planos arquitectónicos",
        "Planos eléctricos",
        "Planos hidráulicos",
        "Carta de liberación de hipoteca",
        "Constancia de habitabilidad",
        "Permiso municipal de construcción",
        "Contrato con CFE (suministro)",
        "Contrato de servicio de agua potable",
        "Constancia de propiedad",
        "Copia certificada de escritura",
        "Carta de entrega de llaves",
        "Cesión de derechos de inmueble",
        "Notificación de escrituración",
        "Póliza de garantía estructural",
        "Certificado energético habitacional",
        "Oficio del notario público",
        "Acta de asamblea de condóminos",
        "Padrón de condóminos",
        "Constancia de alineamiento y número oficial",
        "Comprobante de pago de derechos catastrales",
        "Cédula catastral",
        "Plano catastral",
        "Dictamen de Protección Civil para vivienda",
        "Constancia de terminación de obra",
        "Permiso de demolición",
        "Contrato de fumigación del inmueble",
        "Reporte de inspección de gas",
    ],
    "Laboral": [
        "Contrato laboral",
        "Carta de recomendación",
        "Recibo de nómina",
        "Constancia de trabajo",
        "Carta de antigüedad",
        "Carta de renuncia",
        "Finiquito laboral",
        "Carta de liquidación",
        "Comprobante de pago de salario",
        "Comprobante de retención de ISR",
        "Constancia de situación fiscal",
        "RFC con homoclave",
        "Alta ante el IMSS (movimiento afiliatorio)",
        "Baja ante el IMSS (movimiento afiliatorio)",
        "Comprobante de vacaciones",
        "Comprobante de aguinaldo",
        "Comprobante de reparto de utilidades (PTU)",
        "Constancia de percepciones y deducciones",
        "Comprobante de capacitación",
        "Diploma laboral",
        "Evaluación de desempeño",
        "Constancia de habilidades laborales",
        "Constancia de capacitación STPS",
        "Constancia de riesgos de trabajo",
        "Credencial del sindicato",
        "Contrato colectivo de trabajo (copia)",
        "Reglamento interno de trabajo (copia)",
        "Acta administrativa",
        "Convenio de terminación laboral",
        "Aviso de despido",
        "Demanda laboral (copia)",
        "Resolución de la Junta de Conciliación (copia)",
        "Carta de cambio de puesto",
        "Aviso de vacaciones autorizadas",
        "Plan de capacitación anual",
        "Reporte de incidencias",
        "Justificante laboral",
        "Solicitud de permiso laboral",
        "Acuerdo de confidencialidad (NDA)",
        "Solicitud de empleo",
        "Currículum vitae",
        "Carta de presentación",
        "Carta de aceptación laboral",
        "Contrato por honorarios",
        "Recibo de honorarios",
        "Opinión de cumplimiento SAT",
        "Opinión de cumplimiento IMSS",
        "Constancia de inscripción patronal (copia)",
        "CFDI de nómina",
        "CFDI de honorarios",
        "Carta responsiva laboral",
        "Política de protección de datos del empleador",
        "Acuse de alta en RFC (SAT)",
        "Acuse de actualización de actividades fiscales",
        "Comprobante de afiliación a caja de ahorro",
        "Carta de objetivos y metas anuales",
    ],
    "Salud": [
        "Carnet del IMSS",
        "Carnet del ISSSTE",
        "Comprobante de afiliación INSABI",
        "Receta médica",
        "Incapacidad laboral",
        "Certificado médico",
        "Resultados de laboratorio",
        "Estudios de rayos X",
        "Ultrasonido",
        "Tomografía",
        "Resonancia magnética",
        "Análisis de sangre",
        "Comprobante de consulta médica",
        "Informe médico",
        "Carta de alta médica",
        "Diagnóstico médico",
        "Historial clínico",
        "Cartilla Nacional de Vacunación",
        "Comprobante de vacunación COVID-19",
        "Certificado de salud escolar",
        "Receta de control",
        "Carnet de citas médicas",
        "Comprobante de cita médica",
        "Informe de especialista",
        "Póliza de seguro de gastos médicos mayores",
        "Póliza de seguro de vida (asociada a salud)",
        "Factura hospitalaria",
        "Recibo de laboratorio clínico",
        "Resultados de estudios de gabinete",
        "Certificado de aptitud física",
        "Certificado de defunción médica",
        "Certificado psicológico",
        "Informe psiquiátrico",
        "Certificado de incapacidad permanente",
        "Constancia de atención psicológica",
        "Informe odontológico",
        "Receta dental",
        "Presupuesto dental",
        "Radiografía dental",
        "Control prenatal",
        "Expediente pediátrico",
        "Carnet perinatal",
        "Resultado de papanicolaou",
        "Resultado de mamografía",
        "Examen de la vista",
        "Receta oftalmológica",
        "Prescripción de lentes",
        "Resultado de glucosa",
        "Resultado de colesterol",
        "Informe de control de peso",
        "Expediente clínico digital",
        "Póliza de seguro funerario",
        "Constancia de tratamiento médico",
        "Reporte de hospitalización",
        "Hoja de egreso hospitalario",
        "Presupuesto médico",
        "Consentimiento quirúrgico",
        "Carta de donación de órganos",
        "Tarjeta de grupo sanguíneo",
        "Bitácora de medicamentos",
    ],
    "Vehicular": [
        "Licencia de conducir",
        "Tarjeta de circulación",
        "Factura del vehículo",
        "Póliza de seguro vehicular",
        "Certificado de verificación vehicular",
        "Refrendo vehicular",
        "Tenencia vehicular",
        "Alta vehicular",
        "Baja vehicular",
        "Placas",
        "Comprobante de cambio de propietario",
        "Comprobante de pago de multa",
        "Resolución de multa de tránsito",
        "Contrato de compraventa vehicular",
        "Reporte de robo vehicular",
        "Dictamen de recuperación de vehículo",
        "Dictamen de valuación vehicular",
        "Reporte de siniestro",
        "Carta de liberación de adeudo vehicular",
        "Factura de refacciones",
        "Recibo de mantenimiento",
        "Recibo de servicio mecánico",
        "Póliza de seguro de responsabilidad civil vehicular",
        "Carta responsiva vehicular",
        "Permiso provisional para circular",
        "Constancia de inscripción REPUVE",
        "Comprobante del número de serie (VIN)",
        "Constancia de no robo",
        "Póliza de cobertura amplia",
        "Comprobante de pago de infracción",
        "Contrato de arrendamiento vehicular",
        "Contrato de financiamiento automotriz",
        "Carta de no adeudo vehicular",
        "Carta finiquito de crédito automotriz",
        "Estado de cuenta de crédito automotriz",
        "Recibo de pago de verificación",
        "Recibo de pago de tenencia",
        "Permiso internacional para conducir",
        "Formato de transferencia vehicular",
        "Carta poder para trámite vehicular",
        "Recibo de gestoría vehicular",
        "Fotografías del vehículo",
        "Dictamen de valuador automotriz",
        "Cotización de seguro automotriz",
        "Cotización de refacciones",
        "Manual del vehículo",
        "Tarjeta de garantía automotriz",
        "Bitácora de mantenimiento",
        "Factura de llantas",
        "Factura de alineación y balanceo",
        "Constancia de afinación",
        "Póliza de asistencia vial",
        "Constancia de bajas de placas",
        "Certificado de emisiones contaminantes",
        "Comprobante de pago de derechos vehiculares",
        "Oficio de liberación de corralón",
        "Reporte de peritaje vehicular",
        "Tarjeta IAVE/Telepeaje",
        "Registro de dispositivo GPS",
        "Contrato de seguro de daños materiales",
    ],
}
